set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(QNX_QCC_ARCH gcc_ntox86_64)
set(QNX_TARGET_ARCH_DIR x86_64)
set(TARGET_PLATFORM QNX7)

include("${CMAKE_CURRENT_LIST_DIR}/Toolchain-QNX7-QCC-Base.cmake")

set(CMAKE_CXX_FLAGS "-stdlib=libstdc++" CACHE STRING "" FORCE)
